export const locations = {
  Arabic: 'ar',
  Bengali: 'bn',
  Bulgarian: 'bg',
  Chinese: 'zh',
  Czech: 'cs',
  Danish: 'da',
  Dutch: 'nl',
  Finnish: 'fi',
  French: 'fr',
  German: 'de',
  Greek: 'el',
  Hindi: 'hi',
  Hungarian: 'hu',
  Italian: 'it',
  Japanese: 'ja',
  Javanese: 'jv',
  Korean: 'ko',
  Mandarin: 'zh_cmn',
  Marathi: 'mr',
  Polish: 'pl',
  Portuguese: 'pt',
  Punjabi: 'pa',
  Romanian: 'ro',
  Russian: 'ru',
  Serbian: 'sr',
  Sinhalese: 'si',
  Slovak: 'sk',
  Spanish: 'es',
  Swedish: 'sv',
  Tamil: 'ta',
  Telugu: 'te',
  Turkish: 'tr',
  Ukrainian: 'uk',
  Urdu: 'ur',
  Vietnamese: 'vi',
  Wu: 'zh_wuu',
  Xiang: 'zh_hsn',
  Yue: 'zh_yue',
  Zulu: 'zu',
}


export const chartColor = [
  "#ffbb11",
  "#ecf0f1",
  "#ba16cc",
  "#50AF95",
  "#1cacfa",
  "#2a71d0",
  "#fc8c03",
  "#db5e77",
]
